language: node_js
node_js:
  - "8"
before_script:
  - "npm i"
script:
  - "npm run build"
cache: npm
deploy:
  local_dir: "./output"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
